config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:registrations],  controllers: {registrations: 'users/registrations'}
  as :user do

    get   '/join' => 'users/registrations#new',    as: 'new_user_registration'
    post  '/join' => 'users/registrations#create', as: 'user_registration'

  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'rooms#index'

  resources :rooms do
    resources :messages
  end
  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  after_create_commit { MessageRelayJob.perform_later(self) }
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages
end

app/models/user.rb
class User < ApplicationRecord
  include Redis::Objects
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable

  sorted_set :online, global: true
  sorted_set :away, global: true

  def short_name
    words = name.split(' ')
    words.first.first + words.last.first
  end

  def appear
    User.online.add(id, id)
  end

  def disappear
    User.online.delete(id)
  end

  def away
    User.away.add(id, id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!, only: [:create, :edit, :update, :destroy]
  before_action :set_message, only: [:show, :edit, :update, :destroy]
  before_action :set_room, only: [:create, :new, :index, :edit]
  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)
    @message.room = @room
    @message.user = current_user

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
        format.js { head :no_content }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    def set_room
      @room = Room.find(params[:room_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:text)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :edit, :update, :destroy]
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @room = Room.first
    redirect_to @room unless @room.nil?
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
    @rooms = Room.all
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.includes(:messages).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:name, :description)
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_filter :configure_permitted_parameters

  respond_to :json, :html

  def new
    build_resource({})
    respond_with self.resource
  end

  def join_with_social
  end

  def create
    super
  end

  def edit
    super
  end

  def update
    @user = resource
    @registration = resource
    authorize @user
    @user.update_with_password(devise_parameter_sanitizer.sanitize(:account_update))
    if @user.encrypted_password_changed?
      set_flash_message :notice, :updated
      sign_in @user, :bypass => true
      render :edit
    else
      render "edit"
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :username, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me, :password_confirmation) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :terms_accepted, :username, :email, :password, :password_confirmation, :current_password) }
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails5 Demo Application</title>
    <meta name="description" content="Rails5 demo application that demostrate action cable and new rails 5 features">
    <meta name="current_user" id="<%= current_user.try(:id) %>" username="<%= current_user.try(:name) %>" badge="<%= current_user.try(:short_name) %>" email="<%= current_user.try(:email) %>">
    <meta name="logged_in" authenticated="<%= user_signed_in? %>" />
    <meta name="env" env="<%= Rails.env %>" />
    <link rel="dns-prefetch" href="https://oss.maxcdn.com/" />
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>
  <body>
    <div class="header">
      <div class="team-menu">
        RealChat
      </div>
      <div class="channel-menu">
        <span class="channel-menu_name">
          <span class="channel-menu_prefix">#</span>
          slack
        </span>
      </div>
    </div>
    <div class="main">
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="message" data-id="<%= message.id %>" data-user-id="<%= message.user_id %>">
  <a href="" class="message_profile-pic">
    <i class="material-icons circle red"><%= message.user.short_name %></i>
  </a>
  <a href="" class="message_username"><%= message.user.name %></a>
  <span class="message_timestamp"><%= message.created_at %></span>
  <span class="message_star"></span>
  <span class="message_content"><%= message.text %></span>
</div>

app/views/rooms/_form.html.erb
<%= content_tag :div, class: 'row' do %>
  <%= form_for(room, html: { class: 'col s6' }) do |f| %>
    <% if room.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

        <ul>
        <% room.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="row">
      <div class="input-field">
        <%= f.text_field :name, placeholder: "Enter room name" %>
      </div>
    </div>

    <div class="row">
      <div class="input-field">
        <%= f.text_area :description, class: 'materialize-textarea', placeholder: "Enter room description" %>
      </div>
    </div>

    <div class="actions">
      <%= f.submit 'Create room',  class: 'btn waves-effect waves-light' %>
    </div>
  <% end %>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<div class="row">
  <div class="col s6">
    <div class="collection">
      <h1>Loading rooms...</h1>
    </div>
  </div>
</div>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<div class="listings">
  <div class="listings_channels">
    <h2 class="listings_header">Channels</h2>
    <ul class="channel_list">
      <% @rooms.each do |room| %>
      <li class="channel active">
        <a class="channel_name">
          <span class="unread">
            0
          </span>
          <span>
            <span class="prefix">#</span>
            <%= room.name %>
          </span>
        </a>
      </li>
      <% end %>
    </ul>

  </div>
  <div class="listings_direct-messages"></div>
  <p class="disclaimer">This demo is not created by, affiliated with, or supported by Slack Technologies, Inc.</p>
</div>

<div class="message-history" data-channel='room' data-room-id="<%= @room.id %>">
  <% @room.messages.includes(:user).each do |message| %>
    <%= render partial: 'messages/message', locals: {message: message} %>
  <% end %>
</div>

<div class="footer">
  <div class="user-menu">
    <span class="user-menu_profile-pic"></span>
    <% if user_signed_in? %>
      <span class="user-menu_username"><a href="#"><%= current_user.name %></a></span>
    <% else %>
      <span class="user-menu_username"><%= link_to('Log in', new_user_session_path) %></span>
    <% end %>
    <span id="user-status-<%= current_user.id %>" class="user-status icon"></span>
    <span class="connection_status">online</span>
  </div>
  <div class="input-box">
    <%= form_for([@room, Message.new], remote: true) do |f| %>
      <%= f.text_area :text, class: 'input-box_text', placeholder: "Enter message", data: {behavior: "room_speaker" } %>
    <% end %>
  </div>
</div>